apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels: 
    group: db
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: pgadmin
  ports:
    - port: 80          # port exposed outside ClusterIP
      targetPort: 80    # port exposed by Pod